### ISSUE TITLE
Download of pre-compiled binaries not possible

### ISSUE THREAD

**Issue by sergejzr** [richarda23/rspace-cli#7]
Dear Team,
At the moment it is not possible to download any of the pre-compiled binaries from Bintray (it is forbidden).
Do you plan to re-host them?
Best regards
Sergej

**Comment by richarda23** [comment]
Hi Sergej

Yes, Bintray just closed their hosting service. This project is now forked at https://github.com/rspace-os/rspace-cli
and downloads will be available on ResearchSpace download site. If you contact me via work email (richardATresearchspace.com) I will send you credentials for accessing binaries directly. Thanks for raising this, I will update the README files

**Comment by richarda23** [comment]
Binary builds are now available from ResearchSpace download site on. request
